### ISSUE TITLE
VT purl does not point to latest release 

### ISSUE THREAD

**Issue by matentzn** [AnimalGenome/vertebrate-trait-ontology#3]
Good day! I noticed that
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/vt.yml redirects the VT ontology to the uPheno repo. Your [OBO metadata](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/vt.md) suggests that this repo here is the rightful home of VT, so we should change the above ASAP. One of the consequences is tools like ontobee or OLS which are used to browser are ontologies are not up to date with VT anymore! But basically anyone who is referring to VT by its purl (http://purl.obolibrary.org/obo/vt.owl) is now using an out-of-date version.

https://www.ebi.ac.uk/ols/ontologies/vt
http://www.ontobee.org/ontology/VT

Assuming that this indeed IS the right VT repo, would you want us to redirect the OBO purl here instead? If so, we need you to do one thing (I can take care of the rest): create a file called "vt.owl" somewhere in your repo, for example in a directory called "current release" which you always remember to overwrite when you have a new release. So for example, you want to add VT version 10, you would do as you did so far, and then *overwrite the file vt.owl with the VT-10.0.owl file* so that we can have a stable url to point to. What do you think? Happy to help.

**Comment by matentzn** [comment]
@cmungall FYI

**Comment by henrietteharmse** [comment]
This issue results in an old version VT to be displayed on OLS.

**Comment by jonquet** [comment]
We experience the same problem with AgroPortal. And I assume BioPortal too. 

So I would recommend: 
- store the version in the owl:versionInfo property (so that our portal will automatically get it)
- always maintain the last version in a file called « VT.owl » or « VT_latest.owl » and only rename it to VT_X.owl when you create another latest version
- fix the PURL to point to https://github.com/AnimalGenome/vertebrate-trait-ontology/blob/master/VT_latest.owl
- let us all know (by closing this issue)

**Comment by zhilianghu** [comment]
Sorry for the overlook.  Please take a look in the "current_release" folder.  Is this something that can work for you as a "stable version"?  We will keep files in this location to be up to date.  Thank you all!

**Comment by matentzn** [comment]
Thats perfect! just make sure you keep it updated. Thanks :)
